services:
  langgraph:
    build: .
    container_name: langgraph-app
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: gemma3:1b

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: